import {
  AirplaneTilt,
  Archive,
  Article,
  Bank,
  Barbell,
  BookOpen,
  BookmarkSimple,
  Briefcase,
  Bug,
  Camera,
  Certificate,
  ChartBar,
  ChartLineUp,
  ChatCircleDots,
  Circuitry,
  Cloud,
  Code,
  Compass,
  Cpu,
  CreditCard,
  CurrencyDollar,
  Database,
  Flask,
  FolderOpen,
  Funnel,
  GameController,
  GitBranch,
  GlobeHemisphereWest,
  GraduationCap,
  Headphones,
  Heart,
  Heartbeat,
  House,
  Image,
  Lightbulb,
  ListChecks,
  MagicWand,
  MapPin,
  MapTrifold,
  Megaphone,
  MusicNotes,
  Newspaper,
  Notebook,
  Palette,
  PenNib,
  Robot,
  RocketLaunch,
  ShoppingBag,
  Stack,
  Star,
  Storefront,
  Tag,
  Target,
  TerminalWindow,
  TextT,
  Translate,
  TrendUp,
  UsersThree,
  VideoCamera,
  Wallet,
  Wrench,
  type IconProps,
} from "@phosphor-icons/react";
import type { ComponentType } from "react";
import type { CategoryIcon } from "@/domain/types";

export type CategoryIconGroup =
  | "通用"
  | "工作"
  | "技术"
  | "AI"
  | "知识"
  | "设计"
  | "增长"
  | "商业"
  | "生活"
  | "娱乐"
  | "旅行";

export const CATEGORY_ICON_GROUPS: readonly CategoryIconGroup[] = [
  "通用",
  "工作",
  "技术",
  "AI",
  "知识",
  "设计",
  "增长",
  "商业",
  "生活",
  "娱乐",
  "旅行",
];

export const CATEGORY_ICON_OPTIONS: ReadonlyArray<{
  value: CategoryIcon;
  label: string;
  group: CategoryIconGroup;
}> = [
  { value: "bookmark", label: "收藏", group: "通用" },
  { value: "layers", label: "资源", group: "通用" },
  { value: "folder", label: "文件夹", group: "通用" },
  { value: "tag", label: "标签", group: "通用" },
  { value: "star", label: "星标", group: "通用" },
  { value: "checklist", label: "任务", group: "通用" },
  { value: "archive", label: "归档", group: "通用" },
  { value: "briefcase", label: "工作", group: "工作" },
  { value: "home", label: "主页", group: "工作" },
  { value: "community", label: "团队", group: "工作" },
  { value: "chat", label: "沟通", group: "工作" },
  { value: "code", label: "开发", group: "技术" },
  { value: "terminal", label: "终端", group: "技术" },
  { value: "database", label: "数据库", group: "技术" },
  { value: "cloud", label: "云服务", group: "技术" },
  { value: "cpu", label: "计算", group: "技术" },
  { value: "git", label: "版本控制", group: "技术" },
  { value: "bug", label: "调试", group: "技术" },
  { value: "globe", label: "网站", group: "技术" },
  { value: "tools", label: "工具", group: "技术" },
  { value: "robot", label: "AI 机器人", group: "AI" },
  { value: "magic", label: "自动化", group: "AI" },
  { value: "circuitry", label: "模型", group: "AI" },
  { value: "idea", label: "灵感", group: "AI" },
  { value: "rocket", label: "创业", group: "AI" },
  { value: "study", label: "学习", group: "知识" },
  { value: "book", label: "阅读", group: "知识" },
  { value: "notebook", label: "笔记", group: "知识" },
  { value: "certificate", label: "证书", group: "知识" },
  { value: "science", label: "研究", group: "知识" },
  { value: "translate", label: "翻译", group: "知识" },
  { value: "news", label: "资讯", group: "知识" },
  { value: "article", label: "文章", group: "知识" },
  { value: "palette", label: "设计", group: "设计" },
  { value: "image", label: "图片", group: "设计" },
  { value: "camera", label: "摄影", group: "设计" },
  { value: "pen", label: "写作", group: "设计" },
  { value: "typography", label: "字体", group: "设计" },
  { value: "chart", label: "数据", group: "增长" },
  { value: "bars", label: "报表", group: "增长" },
  { value: "trend", label: "增长", group: "增长" },
  { value: "marketing", label: "营销", group: "增长" },
  { value: "target", label: "目标", group: "增长" },
  { value: "funnel", label: "漏斗", group: "增长" },
  { value: "bank", label: "金融", group: "商业" },
  { value: "currency", label: "收益", group: "商业" },
  { value: "credit-card", label: "支付", group: "商业" },
  { value: "wallet", label: "钱包", group: "商业" },
  { value: "storefront", label: "店铺", group: "商业" },
  { value: "shopping", label: "购物", group: "商业" },
  { value: "heart", label: "生活", group: "生活" },
  { value: "health", label: "健康", group: "生活" },
  { value: "fitness", label: "运动", group: "生活" },
  { value: "music", label: "音乐", group: "娱乐" },
  { value: "video", label: "视频", group: "娱乐" },
  { value: "game", label: "游戏", group: "娱乐" },
  { value: "headphones", label: "播客", group: "娱乐" },
  { value: "travel", label: "旅行", group: "旅行" },
  { value: "map", label: "地图", group: "旅行" },
  { value: "compass", label: "导航", group: "旅行" },
  { value: "location", label: "位置", group: "旅行" },
] as const;

const iconMap: Record<CategoryIcon, ComponentType<IconProps>> = {
  briefcase: Briefcase,
  bookmark: BookmarkSimple,
  layers: Stack,
  study: GraduationCap,
  heart: Heart,
  globe: GlobeHemisphereWest,
  code: Code,
  chart: ChartLineUp,
  palette: Palette,
  book: BookOpen,
  home: House,
  news: Newspaper,
  tools: Wrench,
  shopping: ShoppingBag,
  travel: AirplaneTilt,
  music: MusicNotes,
  video: VideoCamera,
  community: UsersThree,
  idea: Lightbulb,
  archive: Archive,
  folder: FolderOpen,
  tag: Tag,
  star: Star,
  checklist: ListChecks,
  terminal: TerminalWindow,
  database: Database,
  cloud: Cloud,
  cpu: Cpu,
  git: GitBranch,
  bug: Bug,
  robot: Robot,
  magic: MagicWand,
  circuitry: Circuitry,
  rocket: RocketLaunch,
  notebook: Notebook,
  certificate: Certificate,
  science: Flask,
  translate: Translate,
  image: Image,
  camera: Camera,
  pen: PenNib,
  typography: TextT,
  bars: ChartBar,
  trend: TrendUp,
  marketing: Megaphone,
  target: Target,
  funnel: Funnel,
  bank: Bank,
  currency: CurrencyDollar,
  "credit-card": CreditCard,
  wallet: Wallet,
  storefront: Storefront,
  health: Heartbeat,
  fitness: Barbell,
  game: GameController,
  headphones: Headphones,
  map: MapTrifold,
  compass: Compass,
  location: MapPin,
  article: Article,
  chat: ChatCircleDots,
};

export function CategoryGlyph({
  name,
  ...props
}: IconProps & { name: CategoryIcon }) {
  const Icon = iconMap[name] ?? BookmarkSimple;
  return <Icon {...props} />;
}
